const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
fs.mkdirSync('artifacts', { recursive: true });
(async () => {
  const browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_CHANNEL ? { channel: process.env.PLAYWRIGHT_CHANNEL } : {}) });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(process.env.PATS_BAR_URL || 'http://127.0.0.1:5173');
  await page.waitForFunction(() => window.__patsBar?.view.hero);
  await page.screenshot({ path: 'artifacts/title.png' });
  await page.locator('[data-action=start]').click();
  await page.waitForTimeout(250);
  await page.waitForFunction(() => window.__patsBar.audio.context?.state === 'running');
  const audioCheck = await page.evaluate(() => {
    const { game, audio } = window.__patsBar; const ctx = audio.context;
    let played = 0, audible = false;
    const createSource = ctx.createBufferSource.bind(ctx);
    ctx.createBufferSource = () => {
      const source = createSource(); const start = source.start.bind(source);
      source.start = (...args) => { played++; audible = source.buffer.getChannelData(0).some(v => Math.abs(v) > .01); start(...args); };
      return source;
    };
    game.damage(1); game.damage(1); const afterHit = played;
    audio.muted = true; game.player.invulnerable = 0; game.damage(1);
    audio.muted = false; ctx.createBufferSource = createSource;
    return { afterHit, afterMute: played, audible };
  });
  assert.deepEqual(audioCheck, { afterHit: 1, afterMute: 1, audible: true });
  const startX = await page.evaluate(() => window.__patsBar.game.player.x);
  await page.keyboard.down('KeyD'); await page.waitForTimeout(400); await page.keyboard.up('KeyD');
  assert.ok(await page.evaluate(() => window.__patsBar.game.player.x) > startX);
  await page.mouse.move(900, 350); await page.mouse.down(); await page.waitForTimeout(450); await page.mouse.up();
  assert.ok(await page.evaluate(() => window.__patsBar.game.shots) > 0);
  await page.keyboard.press('Space'); await page.waitForTimeout(100);
  assert.ok(await page.evaluate(() => window.__patsBar.game.player.dodge) > 0);
  await page.keyboard.press('Escape'); await page.waitForTimeout(100);
  assert.equal(await page.evaluate(() => window.__patsBar.game.mode), 'paused');
  const frozen = await page.evaluate(() => window.__patsBar.game.elapsed); await page.waitForTimeout(200);
  assert.equal(await page.evaluate(() => window.__patsBar.game.elapsed), frozen);
  await page.locator('[data-action=resume]').click();
  // Hold the combat click through level-up and beyond the delay.
  await page.mouse.move(500, 500); await page.mouse.down();
  await page.evaluate(() => { const g = window.__patsBar.game; g.xp = 12; g.checkLevel(); });
  await page.waitForFunction(() => document.querySelectorAll('[data-upgrade]:disabled').length === 3);
  const upgradeTime = await page.evaluate(() => window.__patsBar.game.elapsed);
  await page.waitForTimeout(300);
  assert.equal(await page.locator('[data-upgrade]:disabled').count(), 3, 'Held combat click must keep upgrades locked');
  assert.equal(await page.evaluate(() => window.__patsBar.game.elapsed), upgradeTime, 'Combat stays paused');
  await page.mouse.up();
  await page.waitForFunction(() => document.querySelectorAll('[data-upgrade]:disabled').length === 0);
  assert.equal(await page.evaluate(() => window.__patsBar.game.mode), 'upgrade', 'Releasing the old click must not select anything');
  // A click without a fresh press must also be rejected.
  await page.locator('[data-upgrade]').first().dispatchEvent('click');
  assert.equal(await page.evaluate(() => window.__patsBar.game.mode), 'upgrade');
  await page.screenshot({ path: 'artifacts/upgrades.png' }); await page.locator('[data-upgrade]').first().click();
  await page.evaluate(() => { const g = window.__patsBar.game; for (let i = 0; i < 8; i++) g.spawn(i % 3 ? 'olive' : 'bottle', { x: (i - 4) * 2.3, z: -3 + i % 2 * 3 }); });
  await page.waitForTimeout(500); await page.screenshot({ path: 'artifacts/gameplay.png' });
  await page.evaluate(() => { const g = window.__patsBar.game; g.enemies = []; g.bullets = []; g.wave = 3; g.bannerTime = 0; const b = g.spawn('boss', { x: 0, z: -4 }); b.phase = 'warning'; b.phaseTime = 10; b.target = { ...g.player }; });
  await page.waitForTimeout(100); await page.screenshot({ path: 'artifacts/boss.png' });
  assert.ok(await page.evaluate(() => {
    const { game, view } = window.__patsBar; const b = game.enemies[0];
    const c = Math.cos(view.warningLine.rotation.z), s = Math.sin(view.warningLine.rotation.z);
    const dx = b.target.x - b.x, dz = b.target.z - b.z;
    return Math.abs((-s) * dz - (-c) * dx) < .001;
  }), 'Charge warning must align with the actual target path');
  await page.evaluate(() => { window.__patsBar.game.enemies[0].hp = 0; }); await page.waitForTimeout(100);
  assert.equal(await page.evaluate(() => window.__patsBar.game.mode), 'victory');
  await page.locator('[data-action=start]').click(); await page.waitForTimeout(100);
  assert.equal(await page.evaluate(() => window.__patsBar.game.kills), 0);
  await page.evaluate(() => { window.__patsBar.game.damage(100); }); await page.waitForTimeout(100);
  assert.equal(await page.evaluate(() => window.__patsBar.game.mode), 'defeat');
  await page.locator('[data-action=start]').click(); await page.waitForTimeout(100);
  await page.evaluate(() => window.dispatchEvent(new Event('blur'))); await page.waitForTimeout(100);
  assert.equal(await page.evaluate(() => window.__patsBar.game.mode), 'paused');
  await page.setViewportSize({ width: 900, height: 650 }); await page.waitForTimeout(100);
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  assert.deepEqual(errors, []); console.log('Browser QA passed: movement, mouse fire, dodge, pause, upgrades, boss, win/loss, restart, focus loss, resize; no page errors.');
  await browser.close();
})().catch(e => { console.error(e); process.exitCode = 1; });
